openapi: 3.0.0
info:
  title: GDSC Website API
  version: 1.0.0
  description: An API used for GDSC Chapter Sriwijaya University Website

servers:
  - url: https://gdsc-api.nabiels.my.id/api/v1

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT Authentication for protected resources"

  responses:
    $ref: "./openapi/responses/responses.yml"

  schemas:
    Response:
      $ref: "./openapi/schemas/response.yaml"

    Division:
      $ref: "./openapi/schemas/division.yaml"

    Members:
      $ref: "./openapi/schemas/member.yaml"


tags:
  - name: Divisions
    description: Any API endpoints related to division here
  - name : Members
    description: Any API endpoints to member here
paths:
  /divisions:
    $ref: "./openapi/paths/divisions.yaml"
  /members:
    $ref: "./openapi/paths/members.yaml"


