// Code generated by sqlc. DO NOT EDIT.

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	Uuid      uuid.UUID `json:"uuid"`
	Name      string    `json:"name"`
	Birthdate time.Time `json:"birthdate"`
}
