name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      
      - name: Install dependencies
        run: make tidy APP_MODE=development
      
      - name: Build binary
        run: make build APP_MODE=development

      - name: Upload files to Server
        run: |
          eval $(ssh-agent )
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          scp -o StrictHostKeyChecking=no dist/app .dockerignore Dockerfile docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/app
          ssh-add -D

      - name: Build and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          sync: true
          script: |
            cd ~/app
            docker-compose down
            docker-compose up -d
