name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      
      - name: Install dependencies
        run: make tidy APP_MODE=development
      
      - name: Build binary
        run: make build APP_MODE=development

      - name: Copy binary to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/,docker-compose.yml"
          target: "~/app/"
      
      - name: Run binary in VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app
            docker-compose up -d
